# Resource Definition for the VM Template
source "proxmox-iso" "template" {
 
    # Proxmox Connection Settings
    proxmox_url = "${var.proxmox_api_url}"
    username = "${var.proxmox_api_token_id}"
    token = "${var.proxmox_api_token_secret}"
    insecure_skip_tls_verify = true
    
    # VM General Settings
    node = "pve"
    vm_id = "1000"
    vm_name = "ubuntu-server-22.04.2-packer-template"
    template_description = "Ubuntu server 22.04 template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."

    # VM OS Settings
    os = "l26"
    iso_file = "local:iso/ubuntu-22.04.2-live-server-amd64.iso"
    iso_storage_pool = "local"
    unmount_iso = true

    # VM System Settings
    qemu_agent = true

    # VM Hard Disk Settings
    scsi_controller = "virtio-scsi-single"

    disks {
        disk_size = "10G"
        format = "raw"
        storage_pool = "local-lvm"
        // storage_pool_type = "lvm" #(review this)
        type = "virtio"
    }

    # VM CPU Settings
    cores = "4"
    
    # VM Memory Settings
    memory = "4096" 

    # VM Network Settings
    network_adapters {
        model = "virtio"
        bridge = "vmbr0"
        firewall = "false"
    } 

    # VM Cloud-Init Settings
    cloud_init = false
    cloud_init_storage_pool = "local-lvm"

    boot_wait = "5s"

    # PACKER Boot Commands
    // boot_command = [
    //     "c",
    //     "linux /casper/vmlinuz --- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ",
    //     "<enter><wait>",
    //     "initrd /casper/initrd<enter><wait30>",
    //     "boot<enter>"
    // ]

    boot_command = ["c", "file=/casper/initrd<enter>", "echo $file<enter>", "linux /casper/vmlinuz -- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/'", "<enter><wait><wait>", "initrd $file", "<enter><wait><wait>", "boot<enter>"]
    
    # PACKER Autoinstall Settings
    http_directory = "http" 

    # (Option 1) Add your Password here
    // ssh_password = "password"
    # - or -
    # (Option 2) Add your Private SSH KEY file here
    // ssh_private_key_file = "~/.ssh/id_ed25519_gfranchini"

    ssh_username = "gfranchini"
    ssh_password = "packer"
    # Raise the timeout, when installation takes longer
    ssh_timeout = "30m"
}